
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
#   base_url: example.duckdns.org:8123
    ip_ban_enabled: true
    login_attempts_threshold: 5

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Redirect output to Synology NAS Maria DB
recorder:
    db_url: !secret recorder_db_url
    purge_keep_days: 60
    commit_interval: 30

logger:
  default: info
#  logs:
#    homeassistant.components.synology_dsm: debug
#    synology_dsm: debug

discovery:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: hass
  username: hass
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state
  tags_attributes:
    - "friendly_name"
    - "area"
    - "device_class"
    
#camera: # use Synology integration instead
#  - platform: synology
#    url: https://192.168.0.155:5001
#    username: !secret synology_username
#    password: !secret synology_password
#    timeout: 15
#    verify_ssl: false

rest_command:
#  surveillance_home_mode_on: # USE switch instead
#    url: !secret surveillance_home_mode_on_url
#    verify_ssl: false
#  surveillance_home_mode_off:
#    url: !secret surveillance_home_mode_off_url
#    verify_ssl: false
  foscam_infra_on:
    url: !secret foscam_infra_on_url
    verify_ssl: false
  foscam_infra_off:
    url: !secret foscam_infra_off_url
    verify_ssl: false
    
light:
  - platform: group
    name: Living Room Lights
    entities:
        - light.dimmable_light_2
        - light.color_temperature_light_4
        - light.dimmable_light_9
  - platform: group
    name: Kitchen Lights
    entities:
        - light.color_temperature_light_3
  - platform: group
    name: Baby Lights
    entities:
        - light.color_temperature_light_8
  - platform: group
    name: Petros Bedside
    entities:
        - light.dimmable_light_10
  - platform: switch
    name: Foscam Plug
    entity_id:
        - switch.on_off_plug_in_unit_7
  - platform: switch
    name: Speakers Plug
    entity_id:
        - switch.on_off_plug_in_unit_6
  - platform: switch
    name: DLink Plug
    entity_id:
        - switch.on_off_plug_in_unit_b2
  - platform: switch
    name: Router Plug
    entity_id:
        - switch.on_off_plug_in_unit_b1

homeassistant:
    customize:
        binary_sensor.openclose_5:
            device_class: door
        media_player.sony_bravia_tv:
            device_class: tv
            icon: mdi:television
        media_player.sonytv:
            device_class: tv
            icon: mdi:television
        light.living_room_lights:
            friendly_name: "Living Room Lights"
            icon: mdi:lamps
        light.baby_lights:
            friendly_name: "Baby Lights"
            icon: mdi:human-baby-changing-table
        group.christmas_lights:
            friendly_name: "Christmas Lights"
            icon: mdi:string-lights
        light.petros_bedside:
            friendly_name: "Petros Bedside Lamp"
            icon: mdi:lamp
        light.foscam_plug:
            friendly_name: "Foscam Plug"
            icon: mdi:power-socket-uk
        light.dlink_plug:
            friendly_name: "DLink Plug"
            icon: mdi:power-socket-uk
        light.router_plug:
            friendly_name: "Router Plug"
            icon: mdi:power-socket-uk
        light.speakers_plug:
            friendly_name: "Speakers Plug"
            icon: mdi:speaker
            
notify:
  - platform: group
    name: all_phones
    services:
      - service: mobile_app_1_7pro
      - service: mobile_app_oneplus_a5010
    
switch:
  - platform: template
    switches:
      foscam_night:
        availability_template: "{{ not is_state('camera.kane_nas_foscam_r2m', 'unavailable') }}"
        turn_on:
          service: rest_command.foscam_infra_on
        turn_off:
          service: rest_command.foscam_infra_off

media_player:
  - platform: braviatv_psk
    host: 192.168.0.153
    psk: !secret sony_bravia_psk
    android: True
    user_labels: True
    name: SonyTV
  - platform: androidtv
    name: Sony Android TV
    host: 192.168.0.153
    exclude_unnamed_apps: true
    
lovelace:
  mode: yaml
#  dashboards:
#    lovelace-home:
#      mode: yaml
#      title: Home
#      icon: mdi:home
#      show_in_sidebar: true
#      filename: lovelace-home.yaml    

sensor:
#  - platform: sql
#    db_url: !secret home_db
#    scan_interval: 3600
#    queries:
#      - name: "Crypto Asset GBP"
#        query: 'SELECT SUM(`value`) AS value, `currency` FROM `crypto` WHERE `currency` = "GBP";'
#        column: "value"
#      - name: "Crypto Asset EUR"
#        query: 'SELECT SUM(`value`) AS value, `currency` FROM `crypto` WHERE `currency` = "EUR";'
#        column: "value"
#      - name: "Crypto Asset XBT"
#        query: 'SELECT SUM(`value`) AS value, `currency` FROM `crypto` WHERE `currency` = "XBT";'
#        column: "value"
#      - name: "Crypto Asset ETH"
#        query: 'SELECT SUM(`value`) AS value, `currency` FROM `crypto` WHERE `currency` = "ETH";'
#        column: "value"
#      - name: "Crypto Asset LTC"
#        query: 'SELECT SUM(`value`) AS value, `currency` FROM `crypto` WHERE `currency` = "LTC";'
#        column: "value"
#      - name: "Crypto Asset ADA"
#        query: 'SELECT SUM(`value`) AS value, `currency` FROM `crypto` WHERE `currency` = "ADA";'
#        column: "value"
#      - name: "Crypto Asset MINA"
#        query: 'SELECT SUM(`value`) AS value, `currency` FROM `crypto` WHERE `currency` = "MINA";'
#        column: "value"
  - platform: history_stats
    name: TV_daily_view_time
    entity_id: media_player.sony_android_tv
    state: 'playing'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'